In [1]:
import numpy as np

In [41]:
with open('colliders.csv') as f:
    line = np.array(f.readline().replace(',', ' ').split())
    line = line[[1,3]]
    lat0, lon0 = np.asarray(line, dtype=np.float64)
    
print(lat0, lon0)



37.79248 -122.39745


In [53]:
cells = [(1, 4), (0, 3), (0, 2), (1, 1), (2, 0), (2, 1), (3, 2)]
grid = np.random.randint(0,2,(5,5))

cells = np.transpose(cells)
print(grid)
print(grid[cells[0], cells[1]])
np.sum(grid[cells[0], cells[1]])

[[0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 1 1 1]
 [0 0 1 1 1]
 [0 1 0 0 0]]
[1 0 1 0 0 0 1]


3